name: superexam
description: A student exam management mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The version follows semantic versioning - major.minor.patch
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  percent_indicator:
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications:

  # State management
  provider: ^6.0.5

  # Network and API
  http: ^1.1.0
  dio: ^5.3.0
  connectivity_plus: ^4.0.2

  # Storage
  shared_preferences: ^2.2.0

  # Time and formatting
  intl: ^0.18.1
  timeago: ^3.5.0

  # Utils
  url_launcher: ^6.1.12
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

#  # Assets
  assets:
    - assets/images/
    - assets/data/questions.json

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700